name: Deploy static dist branch

on:
  push:
    branches:
      - main

permissions:
  contents: write # ✅ needed to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # Optional: copy index.html to 404.html for SPA support
      - name: Add SPA fallback
        run: cp dist/index.html dist/404.html

      - name: Deploy dist to gh-pages branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create a temporary working directory
          rm -rf ../gh-pages
          mkdir ../gh-pages
          cp -r dist/* ../gh-pages/

          cd ../gh-pages
          git init
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
